// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bc.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Op int32

const (
	Op_GET  Op = 0
	Op_SEND Op = 1
)

var Op_name = map[int32]string{
	0: "GET",
	1: "SEND",
}

var Op_value = map[string]int32{
	"GET":  0,
	"SEND": 1,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}

func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// Represent a void message indicating success
type Success struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Success) Reset()         { *m = Success{} }
func (m *Success) String() string { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()    {}
func (*Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{1}
}

func (m *Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Success.Unmarshal(m, b)
}
func (m *Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Success.Marshal(b, m, deterministic)
}
func (m *Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Success.Merge(m, src)
}
func (m *Success) XXX_Size() int {
	return xxx_messageInfo_Success.Size(m)
}
func (m *Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Success proto.InternalMessageInfo

func (m *Success) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

// Represents an error.
type Error struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Transaction struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	V                    string   `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{3}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Transaction) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

// A single Block on a Blockchain
type Block struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            string         `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PrevHash             string         `protobuf:"bytes,3,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	Hash                 string         `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Tx                   []*Transaction `protobuf:"bytes,5,rep,name=tx,proto3" json:"tx,omitempty"`
	Seed                 string         `protobuf:"bytes,6,opt,name=seed,proto3" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{4}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Block) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Block) GetPrevHash() string {
	if m != nil {
		return m.PrevHash
	}
	return ""
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetTx() []*Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *Block) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

// Input to AppendBlock
type AppendBlockArgs struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Blockchain           []*Block `protobuf:"bytes,2,rep,name=blockchain,proto3" json:"blockchain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendBlockArgs) Reset()         { *m = AppendBlockArgs{} }
func (m *AppendBlockArgs) String() string { return proto.CompactTextString(m) }
func (*AppendBlockArgs) ProtoMessage()    {}
func (*AppendBlockArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{5}
}

func (m *AppendBlockArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendBlockArgs.Unmarshal(m, b)
}
func (m *AppendBlockArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendBlockArgs.Marshal(b, m, deterministic)
}
func (m *AppendBlockArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendBlockArgs.Merge(m, src)
}
func (m *AppendBlockArgs) XXX_Size() int {
	return xxx_messageInfo_AppendBlockArgs.Size(m)
}
func (m *AppendBlockArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendBlockArgs.DiscardUnknown(m)
}

var xxx_messageInfo_AppendBlockArgs proto.InternalMessageInfo

func (m *AppendBlockArgs) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *AppendBlockArgs) GetBlockchain() []*Block {
	if m != nil {
		return m.Blockchain
	}
	return nil
}

type AppendBlockRet struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendBlockRet) Reset()         { *m = AppendBlockRet{} }
func (m *AppendBlockRet) String() string { return proto.CompactTextString(m) }
func (*AppendBlockRet) ProtoMessage()    {}
func (*AppendBlockRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{6}
}

func (m *AppendBlockRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendBlockRet.Unmarshal(m, b)
}
func (m *AppendBlockRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendBlockRet.Marshal(b, m, deterministic)
}
func (m *AppendBlockRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendBlockRet.Merge(m, src)
}
func (m *AppendBlockRet) XXX_Size() int {
	return xxx_messageInfo_AppendBlockRet.Size(m)
}
func (m *AppendBlockRet) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendBlockRet.DiscardUnknown(m)
}

var xxx_messageInfo_AppendBlockRet proto.InternalMessageInfo

func (m *AppendBlockRet) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AppendTransactionArgs struct {
	Peer                 string       `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Tx                   *Transaction `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AppendTransactionArgs) Reset()         { *m = AppendTransactionArgs{} }
func (m *AppendTransactionArgs) String() string { return proto.CompactTextString(m) }
func (*AppendTransactionArgs) ProtoMessage()    {}
func (*AppendTransactionArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{7}
}

func (m *AppendTransactionArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendTransactionArgs.Unmarshal(m, b)
}
func (m *AppendTransactionArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendTransactionArgs.Marshal(b, m, deterministic)
}
func (m *AppendTransactionArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendTransactionArgs.Merge(m, src)
}
func (m *AppendTransactionArgs) XXX_Size() int {
	return xxx_messageInfo_AppendTransactionArgs.Size(m)
}
func (m *AppendTransactionArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendTransactionArgs.DiscardUnknown(m)
}

var xxx_messageInfo_AppendTransactionArgs proto.InternalMessageInfo

func (m *AppendTransactionArgs) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *AppendTransactionArgs) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type AppendTransactionRet struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendTransactionRet) Reset()         { *m = AppendTransactionRet{} }
func (m *AppendTransactionRet) String() string { return proto.CompactTextString(m) }
func (*AppendTransactionRet) ProtoMessage()    {}
func (*AppendTransactionRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{8}
}

func (m *AppendTransactionRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendTransactionRet.Unmarshal(m, b)
}
func (m *AppendTransactionRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendTransactionRet.Marshal(b, m, deterministic)
}
func (m *AppendTransactionRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendTransactionRet.Merge(m, src)
}
func (m *AppendTransactionRet) XXX_Size() int {
	return xxx_messageInfo_AppendTransactionRet.Size(m)
}
func (m *AppendTransactionRet) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendTransactionRet.DiscardUnknown(m)
}

var xxx_messageInfo_AppendTransactionRet proto.InternalMessageInfo

func (m *AppendTransactionRet) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ProposeBlockArgs struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Round                int64    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Period               int64    `protobuf:"varint,3,opt,name=period,proto3" json:"period,omitempty"`
	Flag                 string   `protobuf:"bytes,4,opt,name=flag,proto3" json:"flag,omitempty"`
	Credence             int64    `protobuf:"varint,5,opt,name=credence,proto3" json:"credence,omitempty"`
	Q                    []byte   `protobuf:"bytes,6,opt,name=q,proto3" json:"q,omitempty"`
	NextQ                []byte   `protobuf:"bytes,7,opt,name=nextQ,proto3" json:"nextQ,omitempty"`
	HashOfLastBlock      string   `protobuf:"bytes,8,opt,name=hashOfLastBlock,proto3" json:"hashOfLastBlock,omitempty"`
	HashOfCurrentBlock   string   `protobuf:"bytes,9,opt,name=hashOfCurrentBlock,proto3" json:"hashOfCurrentBlock,omitempty"`
	Block                *Block   `protobuf:"bytes,10,opt,name=block,proto3" json:"block,omitempty"`
	Signature            *SIGRet  `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposeBlockArgs) Reset()         { *m = ProposeBlockArgs{} }
func (m *ProposeBlockArgs) String() string { return proto.CompactTextString(m) }
func (*ProposeBlockArgs) ProtoMessage()    {}
func (*ProposeBlockArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{9}
}

func (m *ProposeBlockArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposeBlockArgs.Unmarshal(m, b)
}
func (m *ProposeBlockArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposeBlockArgs.Marshal(b, m, deterministic)
}
func (m *ProposeBlockArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposeBlockArgs.Merge(m, src)
}
func (m *ProposeBlockArgs) XXX_Size() int {
	return xxx_messageInfo_ProposeBlockArgs.Size(m)
}
func (m *ProposeBlockArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposeBlockArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ProposeBlockArgs proto.InternalMessageInfo

func (m *ProposeBlockArgs) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *ProposeBlockArgs) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *ProposeBlockArgs) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *ProposeBlockArgs) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *ProposeBlockArgs) GetCredence() int64 {
	if m != nil {
		return m.Credence
	}
	return 0
}

func (m *ProposeBlockArgs) GetQ() []byte {
	if m != nil {
		return m.Q
	}
	return nil
}

func (m *ProposeBlockArgs) GetNextQ() []byte {
	if m != nil {
		return m.NextQ
	}
	return nil
}

func (m *ProposeBlockArgs) GetHashOfLastBlock() string {
	if m != nil {
		return m.HashOfLastBlock
	}
	return ""
}

func (m *ProposeBlockArgs) GetHashOfCurrentBlock() string {
	if m != nil {
		return m.HashOfCurrentBlock
	}
	return ""
}

func (m *ProposeBlockArgs) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *ProposeBlockArgs) GetSignature() *SIGRet {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ProposeBlockRet struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposeBlockRet) Reset()         { *m = ProposeBlockRet{} }
func (m *ProposeBlockRet) String() string { return proto.CompactTextString(m) }
func (*ProposeBlockRet) ProtoMessage()    {}
func (*ProposeBlockRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{10}
}

func (m *ProposeBlockRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposeBlockRet.Unmarshal(m, b)
}
func (m *ProposeBlockRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposeBlockRet.Marshal(b, m, deterministic)
}
func (m *ProposeBlockRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposeBlockRet.Merge(m, src)
}
func (m *ProposeBlockRet) XXX_Size() int {
	return xxx_messageInfo_ProposeBlockRet.Size(m)
}
func (m *ProposeBlockRet) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposeBlockRet.DiscardUnknown(m)
}

var xxx_messageInfo_ProposeBlockRet proto.InternalMessageInfo

func (m *ProposeBlockRet) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type VoteArgs struct {
	Peer      string  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Value     string  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Round     int64   `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Period    int64   `protobuf:"varint,4,opt,name=period,proto3" json:"period,omitempty"`
	VoteType  string  `protobuf:"bytes,5,opt,name=voteType,proto3" json:"voteType,omitempty"`
	Signature *SIGRet `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	//step
	Step                 int64    `protobuf:"varint,7,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteArgs) Reset()         { *m = VoteArgs{} }
func (m *VoteArgs) String() string { return proto.CompactTextString(m) }
func (*VoteArgs) ProtoMessage()    {}
func (*VoteArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{11}
}

func (m *VoteArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteArgs.Unmarshal(m, b)
}
func (m *VoteArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteArgs.Marshal(b, m, deterministic)
}
func (m *VoteArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteArgs.Merge(m, src)
}
func (m *VoteArgs) XXX_Size() int {
	return xxx_messageInfo_VoteArgs.Size(m)
}
func (m *VoteArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteArgs.DiscardUnknown(m)
}

var xxx_messageInfo_VoteArgs proto.InternalMessageInfo

func (m *VoteArgs) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *VoteArgs) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *VoteArgs) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *VoteArgs) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *VoteArgs) GetVoteType() string {
	if m != nil {
		return m.VoteType
	}
	return ""
}

func (m *VoteArgs) GetSignature() *SIGRet {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *VoteArgs) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

type VoteRet struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteRet) Reset()         { *m = VoteRet{} }
func (m *VoteRet) String() string { return proto.CompactTextString(m) }
func (*VoteRet) ProtoMessage()    {}
func (*VoteRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{12}
}

func (m *VoteRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteRet.Unmarshal(m, b)
}
func (m *VoteRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteRet.Marshal(b, m, deterministic)
}
func (m *VoteRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteRet.Merge(m, src)
}
func (m *VoteRet) XXX_Size() int {
	return xxx_messageInfo_VoteRet.Size(m)
}
func (m *VoteRet) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteRet.DiscardUnknown(m)
}

var xxx_messageInfo_VoteRet proto.InternalMessageInfo

func (m *VoteRet) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SIGRet struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SignedMessage        []byte   `protobuf:"bytes,2,opt,name=signedMessage,proto3" json:"signedMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SIGRet) Reset()         { *m = SIGRet{} }
func (m *SIGRet) String() string { return proto.CompactTextString(m) }
func (*SIGRet) ProtoMessage()    {}
func (*SIGRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{13}
}

func (m *SIGRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SIGRet.Unmarshal(m, b)
}
func (m *SIGRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SIGRet.Marshal(b, m, deterministic)
}
func (m *SIGRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SIGRet.Merge(m, src)
}
func (m *SIGRet) XXX_Size() int {
	return xxx_messageInfo_SIGRet.Size(m)
}
func (m *SIGRet) XXX_DiscardUnknown() {
	xxx_messageInfo_SIGRet.DiscardUnknown(m)
}

var xxx_messageInfo_SIGRet proto.InternalMessageInfo

func (m *SIGRet) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SIGRet) GetSignedMessage() []byte {
	if m != nil {
		return m.SignedMessage
	}
	return nil
}

type RequestBlockChainArgs struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestBlockChainArgs) Reset()         { *m = RequestBlockChainArgs{} }
func (m *RequestBlockChainArgs) String() string { return proto.CompactTextString(m) }
func (*RequestBlockChainArgs) ProtoMessage()    {}
func (*RequestBlockChainArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{14}
}

func (m *RequestBlockChainArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestBlockChainArgs.Unmarshal(m, b)
}
func (m *RequestBlockChainArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestBlockChainArgs.Marshal(b, m, deterministic)
}
func (m *RequestBlockChainArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestBlockChainArgs.Merge(m, src)
}
func (m *RequestBlockChainArgs) XXX_Size() int {
	return xxx_messageInfo_RequestBlockChainArgs.Size(m)
}
func (m *RequestBlockChainArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestBlockChainArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RequestBlockChainArgs proto.InternalMessageInfo

func (m *RequestBlockChainArgs) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

type RequestBlockChainRet struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Blockchain           []*Block `protobuf:"bytes,2,rep,name=blockchain,proto3" json:"blockchain,omitempty"`
	Q                    []byte   `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestBlockChainRet) Reset()         { *m = RequestBlockChainRet{} }
func (m *RequestBlockChainRet) String() string { return proto.CompactTextString(m) }
func (*RequestBlockChainRet) ProtoMessage()    {}
func (*RequestBlockChainRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{15}
}

func (m *RequestBlockChainRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestBlockChainRet.Unmarshal(m, b)
}
func (m *RequestBlockChainRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestBlockChainRet.Marshal(b, m, deterministic)
}
func (m *RequestBlockChainRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestBlockChainRet.Merge(m, src)
}
func (m *RequestBlockChainRet) XXX_Size() int {
	return xxx_messageInfo_RequestBlockChainRet.Size(m)
}
func (m *RequestBlockChainRet) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestBlockChainRet.DiscardUnknown(m)
}

var xxx_messageInfo_RequestBlockChainRet proto.InternalMessageInfo

func (m *RequestBlockChainRet) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *RequestBlockChainRet) GetBlockchain() []*Block {
	if m != nil {
		return m.Blockchain
	}
	return nil
}

func (m *RequestBlockChainRet) GetQ() []byte {
	if m != nil {
		return m.Q
	}
	return nil
}

type NoticeFinalBlockValueArgs struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeFinalBlockValueArgs) Reset()         { *m = NoticeFinalBlockValueArgs{} }
func (m *NoticeFinalBlockValueArgs) String() string { return proto.CompactTextString(m) }
func (*NoticeFinalBlockValueArgs) ProtoMessage()    {}
func (*NoticeFinalBlockValueArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{16}
}

func (m *NoticeFinalBlockValueArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeFinalBlockValueArgs.Unmarshal(m, b)
}
func (m *NoticeFinalBlockValueArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeFinalBlockValueArgs.Marshal(b, m, deterministic)
}
func (m *NoticeFinalBlockValueArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeFinalBlockValueArgs.Merge(m, src)
}
func (m *NoticeFinalBlockValueArgs) XXX_Size() int {
	return xxx_messageInfo_NoticeFinalBlockValueArgs.Size(m)
}
func (m *NoticeFinalBlockValueArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeFinalBlockValueArgs.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeFinalBlockValueArgs proto.InternalMessageInfo

func (m *NoticeFinalBlockValueArgs) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *NoticeFinalBlockValueArgs) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type NoticeFinalBlockValueRet struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeFinalBlockValueRet) Reset()         { *m = NoticeFinalBlockValueRet{} }
func (m *NoticeFinalBlockValueRet) String() string { return proto.CompactTextString(m) }
func (*NoticeFinalBlockValueRet) ProtoMessage()    {}
func (*NoticeFinalBlockValueRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{17}
}

func (m *NoticeFinalBlockValueRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeFinalBlockValueRet.Unmarshal(m, b)
}
func (m *NoticeFinalBlockValueRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeFinalBlockValueRet.Marshal(b, m, deterministic)
}
func (m *NoticeFinalBlockValueRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeFinalBlockValueRet.Merge(m, src)
}
func (m *NoticeFinalBlockValueRet) XXX_Size() int {
	return xxx_messageInfo_NoticeFinalBlockValueRet.Size(m)
}
func (m *NoticeFinalBlockValueRet) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeFinalBlockValueRet.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeFinalBlockValueRet proto.InternalMessageInfo

func (m *NoticeFinalBlockValueRet) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Blockchain struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blockchain) Reset()         { *m = Blockchain{} }
func (m *Blockchain) String() string { return proto.CompactTextString(m) }
func (*Blockchain) ProtoMessage()    {}
func (*Blockchain) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{18}
}

func (m *Blockchain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blockchain.Unmarshal(m, b)
}
func (m *Blockchain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blockchain.Marshal(b, m, deterministic)
}
func (m *Blockchain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blockchain.Merge(m, src)
}
func (m *Blockchain) XXX_Size() int {
	return xxx_messageInfo_Blockchain.Size(m)
}
func (m *Blockchain) XXX_DiscardUnknown() {
	xxx_messageInfo_Blockchain.DiscardUnknown(m)
}

var xxx_messageInfo_Blockchain proto.InternalMessageInfo

func (m *Blockchain) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Result struct {
	// Types that are valid to be assigned to Result:
	//	*Result_Bc
	//	*Result_S
	Result               isResult_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{19}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

type isResult_Result interface {
	isResult_Result()
}

type Result_Bc struct {
	Bc *Blockchain `protobuf:"bytes,1,opt,name=bc,proto3,oneof"`
}

type Result_S struct {
	S *Success `protobuf:"bytes,2,opt,name=s,proto3,oneof"`
}

func (*Result_Bc) isResult_Result() {}

func (*Result_S) isResult_Result() {}

func (m *Result) GetResult() isResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Result) GetBc() *Blockchain {
	if x, ok := m.GetResult().(*Result_Bc); ok {
		return x.Bc
	}
	return nil
}

func (m *Result) GetS() *Success {
	if x, ok := m.GetResult().(*Result_S); ok {
		return x.S
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Result) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Result_Bc)(nil),
		(*Result_S)(nil),
	}
}

// A type for arguments across all operations
type Command struct {
	Operation Op `protobuf:"varint,1,opt,name=operation,proto3,enum=pb.Op" json:"operation,omitempty"`
	// Types that are valid to be assigned to Arg:
	//	*Command_Empty
	//	*Command_Tx
	Arg                  isCommand_Arg `protobuf_oneof:"arg"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{20}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetOperation() Op {
	if m != nil {
		return m.Operation
	}
	return Op_GET
}

type isCommand_Arg interface {
	isCommand_Arg()
}

type Command_Empty struct {
	Empty *Empty `protobuf:"bytes,2,opt,name=empty,proto3,oneof"`
}

type Command_Tx struct {
	Tx *Transaction `protobuf:"bytes,3,opt,name=tx,proto3,oneof"`
}

func (*Command_Empty) isCommand_Arg() {}

func (*Command_Tx) isCommand_Arg() {}

func (m *Command) GetArg() isCommand_Arg {
	if m != nil {
		return m.Arg
	}
	return nil
}

func (m *Command) GetEmpty() *Empty {
	if x, ok := m.GetArg().(*Command_Empty); ok {
		return x.Empty
	}
	return nil
}

func (m *Command) GetTx() *Transaction {
	if x, ok := m.GetArg().(*Command_Tx); ok {
		return x.Tx
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Command) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Command_Empty)(nil),
		(*Command_Tx)(nil),
	}
}

type Response struct {
	Success              string   `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{21}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

type RPState struct {
	Message              []string `protobuf:"bytes,1,rep,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPState) Reset()         { *m = RPState{} }
func (m *RPState) String() string { return proto.CompactTextString(m) }
func (*RPState) ProtoMessage()    {}
func (*RPState) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{22}
}

func (m *RPState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPState.Unmarshal(m, b)
}
func (m *RPState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPState.Marshal(b, m, deterministic)
}
func (m *RPState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPState.Merge(m, src)
}
func (m *RPState) XXX_Size() int {
	return xxx_messageInfo_RPState.Size(m)
}
func (m *RPState) XXX_DiscardUnknown() {
	xxx_messageInfo_RPState.DiscardUnknown(m)
}

var xxx_messageInfo_RPState proto.InternalMessageInfo

func (m *RPState) GetMessage() []string {
	if m != nil {
		return m.Message
	}
	return nil
}

type SLState struct {
	Message              []string `protobuf:"bytes,1,rep,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SLState) Reset()         { *m = SLState{} }
func (m *SLState) String() string { return proto.CompactTextString(m) }
func (*SLState) ProtoMessage()    {}
func (*SLState) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e2a20f8b284799, []int{23}
}

func (m *SLState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SLState.Unmarshal(m, b)
}
func (m *SLState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SLState.Marshal(b, m, deterministic)
}
func (m *SLState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SLState.Merge(m, src)
}
func (m *SLState) XXX_Size() int {
	return xxx_messageInfo_SLState.Size(m)
}
func (m *SLState) XXX_DiscardUnknown() {
	xxx_messageInfo_SLState.DiscardUnknown(m)
}

var xxx_messageInfo_SLState proto.InternalMessageInfo

func (m *SLState) GetMessage() []string {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Op", Op_name, Op_value)
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Success)(nil), "pb.Success")
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*Transaction)(nil), "pb.Transaction")
	proto.RegisterType((*Block)(nil), "pb.Block")
	proto.RegisterType((*AppendBlockArgs)(nil), "pb.AppendBlockArgs")
	proto.RegisterType((*AppendBlockRet)(nil), "pb.AppendBlockRet")
	proto.RegisterType((*AppendTransactionArgs)(nil), "pb.AppendTransactionArgs")
	proto.RegisterType((*AppendTransactionRet)(nil), "pb.AppendTransactionRet")
	proto.RegisterType((*ProposeBlockArgs)(nil), "pb.ProposeBlockArgs")
	proto.RegisterType((*ProposeBlockRet)(nil), "pb.ProposeBlockRet")
	proto.RegisterType((*VoteArgs)(nil), "pb.VoteArgs")
	proto.RegisterType((*VoteRet)(nil), "pb.VoteRet")
	proto.RegisterType((*SIGRet)(nil), "pb.SIGRet")
	proto.RegisterType((*RequestBlockChainArgs)(nil), "pb.RequestBlockChainArgs")
	proto.RegisterType((*RequestBlockChainRet)(nil), "pb.RequestBlockChainRet")
	proto.RegisterType((*NoticeFinalBlockValueArgs)(nil), "pb.NoticeFinalBlockValueArgs")
	proto.RegisterType((*NoticeFinalBlockValueRet)(nil), "pb.NoticeFinalBlockValueRet")
	proto.RegisterType((*Blockchain)(nil), "pb.Blockchain")
	proto.RegisterType((*Result)(nil), "pb.Result")
	proto.RegisterType((*Command)(nil), "pb.Command")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*RPState)(nil), "pb.RPState")
	proto.RegisterType((*SLState)(nil), "pb.SLState")
}

func init() { proto.RegisterFile("bc.proto", fileDescriptor_99e2a20f8b284799) }

var fileDescriptor_99e2a20f8b284799 = []byte{
	// 999 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcf, 0x6e, 0xdb, 0x46,
	0x13, 0x17, 0x49, 0x51, 0xa2, 0x46, 0xfa, 0x6c, 0x7f, 0x1b, 0xbb, 0xa1, 0xd5, 0xb4, 0xb1, 0x37,
	0x29, 0xe0, 0xda, 0x80, 0x1b, 0xa8, 0x3d, 0x14, 0xe8, 0xc9, 0x72, 0x15, 0x3b, 0x85, 0x1b, 0x2b,
	0x2b, 0xc3, 0x77, 0x8a, 0xdc, 0xc8, 0x42, 0x25, 0x92, 0xde, 0x5d, 0x09, 0x0e, 0xd0, 0x97, 0xe8,
	0xa5, 0x87, 0x3e, 0x4b, 0x5f, 0xa1, 0xef, 0x54, 0xcc, 0x2e, 0x29, 0xc9, 0x14, 0xad, 0xa2, 0xe8,
	0x6d, 0x67, 0xe6, 0xb7, 0xb3, 0xbf, 0xf9, 0x4b, 0x82, 0x37, 0x0c, 0x4f, 0x53, 0x91, 0xa8, 0x84,
	0xd8, 0xe9, 0x90, 0xd6, 0xc1, 0xed, 0x4d, 0x53, 0xf5, 0x89, 0x3e, 0x87, 0xfa, 0x60, 0x16, 0x86,
	0x5c, 0x4a, 0xd2, 0x02, 0x4b, 0xfa, 0xd6, 0x81, 0x75, 0xd4, 0x60, 0x96, 0xa4, 0xfb, 0xe0, 0xf6,
	0x84, 0x48, 0x04, 0xd9, 0x01, 0x67, 0x2a, 0x47, 0x99, 0x01, 0x8f, 0xf4, 0x04, 0x9a, 0x37, 0x22,
	0x88, 0x65, 0x10, 0xaa, 0x71, 0x12, 0x93, 0x2d, 0xb0, 0xc7, 0x91, 0xb6, 0x3b, 0xcc, 0x1e, 0x47,
	0xe8, 0x67, 0xee, 0xdb, 0xc6, 0xcf, 0x9c, 0xfe, 0x61, 0x81, 0xdb, 0x9d, 0x24, 0xe1, 0x2f, 0x6b,
	0xb8, 0x17, 0xd0, 0x50, 0xe3, 0x29, 0x97, 0x2a, 0x98, 0xa6, 0x19, 0x7e, 0xa9, 0x20, 0x6d, 0xf0,
	0x52, 0xc1, 0xe7, 0x97, 0x81, 0xbc, 0xf3, 0x1d, 0x6d, 0x5c, 0xc8, 0x84, 0x40, 0xf5, 0x0e, 0xf5,
	0x55, 0xad, 0xd7, 0x67, 0xf2, 0x12, 0x6c, 0xf5, 0xe0, 0xbb, 0x07, 0xce, 0x51, 0xb3, 0xb3, 0x7d,
	0x9a, 0x0e, 0x4f, 0x57, 0x28, 0x32, 0x5b, 0x3d, 0xe0, 0x25, 0xc9, 0x79, 0xe4, 0xd7, 0xcc, 0x25,
	0x3c, 0xd3, 0x3e, 0x6c, 0x9f, 0xa5, 0x29, 0x8f, 0x23, 0xcd, 0xf0, 0x4c, 0x8c, 0x24, 0xc2, 0x52,
	0xce, 0x45, 0x16, 0xaf, 0x3e, 0x93, 0xaf, 0x01, 0x86, 0x08, 0x08, 0xef, 0x82, 0x71, 0xec, 0xdb,
	0xfa, 0x8d, 0x06, 0xbe, 0xa1, 0xaf, 0xb1, 0x15, 0x23, 0x3d, 0x86, 0xad, 0x15, 0x8f, 0x8c, 0x2b,
	0xe2, 0x43, 0x5d, 0x9a, 0x0c, 0x6b, 0x9f, 0x1e, 0xcb, 0x45, 0x7a, 0x05, 0x7b, 0x06, 0xbb, 0x42,
	0xf5, 0x49, 0x0e, 0x26, 0x3e, 0x4c, 0x53, 0x79, 0x7c, 0xf4, 0x0d, 0xec, 0xae, 0x79, 0xdb, 0xfc,
	0xfe, 0x5f, 0x36, 0xec, 0xf4, 0x45, 0x92, 0x26, 0x92, 0x6f, 0x8e, 0x7f, 0x17, 0x5c, 0x91, 0xcc,
	0xe2, 0x48, 0x3f, 0xef, 0x30, 0x23, 0x90, 0xcf, 0xa0, 0x96, 0x72, 0x31, 0x4e, 0x22, 0x5d, 0x1f,
	0x87, 0x65, 0x12, 0x7a, 0xf8, 0x38, 0x09, 0x46, 0x79, 0x75, 0xf0, 0x8c, 0xd5, 0x0c, 0x05, 0x8f,
	0x78, 0x1c, 0x72, 0xdf, 0xd5, 0xe8, 0x85, 0x8c, 0xfd, 0x72, 0xaf, 0xab, 0xd2, 0x62, 0xd6, 0x3d,
	0xbe, 0x15, 0xf3, 0x07, 0xf5, 0xc1, 0xaf, 0x6b, 0x8d, 0x11, 0xc8, 0x11, 0x6c, 0x63, 0x95, 0xaf,
	0x3f, 0x5e, 0x05, 0x52, 0x69, 0xb2, 0xbe, 0xa7, 0xdd, 0x17, 0xd5, 0xe4, 0x14, 0x88, 0x51, 0x9d,
	0xcf, 0x84, 0xe0, 0x71, 0x06, 0x6e, 0x68, 0x70, 0x89, 0x85, 0xbc, 0x04, 0x57, 0x97, 0xcf, 0x07,
	0x9d, 0xda, 0x95, 0xb2, 0x1a, 0x3d, 0x39, 0x82, 0x86, 0x1c, 0x8f, 0xe2, 0x40, 0xcd, 0x04, 0xf7,
	0x9b, 0x1a, 0x04, 0x08, 0x1a, 0xbc, 0xbb, 0x60, 0x5c, 0xb1, 0xa5, 0x91, 0x9e, 0xc0, 0xf6, 0x6a,
	0x3a, 0x37, 0x27, 0xff, 0x4f, 0x0b, 0xbc, 0xdb, 0x44, 0xf1, 0x4d, 0x49, 0x9f, 0x07, 0x93, 0x19,
	0xcf, 0x46, 0xc3, 0x08, 0xcb, 0x52, 0x38, 0xe5, 0xa5, 0xa8, 0x3e, 0x2a, 0x45, 0x1b, 0xbc, 0x79,
	0xa2, 0xf8, 0xcd, 0xa7, 0xd4, 0xa4, 0xbd, 0xc1, 0x16, 0xf2, 0xe3, 0xb8, 0x6a, 0x1b, 0xe2, 0xd2,
	0x93, 0xa3, 0x78, 0xaa, 0x2b, 0xe2, 0x30, 0x7d, 0xa6, 0xaf, 0xa0, 0x8e, 0xec, 0x37, 0xc7, 0xf8,
	0x16, 0x6a, 0xc6, 0x1b, 0x12, 0x9c, 0x49, 0x2e, 0xde, 0x45, 0x59, 0x88, 0x99, 0x44, 0x5e, 0xc3,
	0xff, 0xf0, 0x1d, 0x1e, 0xfd, 0xcc, 0xa5, 0x0c, 0x46, 0x26, 0xd8, 0x16, 0x7b, 0xac, 0xa4, 0x27,
	0xb0, 0xc7, 0xf8, 0xfd, 0x8c, 0x67, 0x35, 0x3e, 0xc7, 0x49, 0x7b, 0x2a, 0x6f, 0x34, 0x84, 0xdd,
	0x35, 0x30, 0x52, 0xf8, 0x6f, 0x83, 0x6d, 0xba, 0xd4, 0xc9, 0xba, 0x94, 0xf6, 0x60, 0xff, 0x7d,
	0xa2, 0xc6, 0x21, 0x7f, 0x3b, 0x8e, 0x83, 0x89, 0x46, 0xdf, 0x62, 0x7d, 0xfe, 0x5d, 0x35, 0xe9,
	0x77, 0xe0, 0x97, 0xba, 0xd9, 0x9c, 0xd6, 0x6f, 0x00, 0xba, 0x4b, 0x62, 0x87, 0x50, 0xd3, 0x34,
	0x11, 0x56, 0xe0, 0x9f, 0x19, 0xe8, 0x07, 0xa8, 0x31, 0x2e, 0x67, 0x13, 0x45, 0x0e, 0xc0, 0x1e,
	0x86, 0xda, 0x5f, 0xb3, 0xb3, 0xb5, 0x00, 0x6a, 0x47, 0x97, 0x15, 0x66, 0x0f, 0x43, 0xf2, 0x39,
	0x7e, 0x05, 0xcc, 0x9a, 0x69, 0xea, 0x76, 0x30, 0x8f, 0x5e, 0x56, 0x98, 0x25, 0xbb, 0x1e, 0xd4,
	0x84, 0x76, 0x44, 0x7f, 0x85, 0xfa, 0x79, 0x32, 0x9d, 0x06, 0x31, 0xd6, 0xb0, 0x91, 0xa4, 0x5c,
	0x04, 0xb8, 0x70, 0xb4, 0xeb, 0xad, 0x4e, 0x0d, 0x6f, 0x5e, 0xa7, 0x6c, 0x69, 0x20, 0x87, 0xe0,
	0x72, 0xfc, 0xe2, 0x64, 0xbe, 0x35, 0x4b, 0xfd, 0x09, 0xba, 0xac, 0x30, 0x63, 0x21, 0x87, 0x7a,
	0xc5, 0x39, 0xa5, 0x2b, 0x0e, 0xd9, 0xa9, 0x87, 0xae, 0x0b, 0x4e, 0x20, 0x46, 0xf4, 0x35, 0x78,
	0x8c, 0xcb, 0x34, 0x89, 0x25, 0xc7, 0x3c, 0x0d, 0x56, 0xf2, 0xd4, 0x60, 0xb9, 0x88, 0x3d, 0xca,
	0xfa, 0x03, 0x15, 0x28, 0x0d, 0xca, 0x3b, 0x0c, 0xb3, 0xd4, 0x60, 0xb9, 0x88, 0xa0, 0xc1, 0xd5,
	0x3f, 0x80, 0x8e, 0x9f, 0x83, 0x7d, 0x9d, 0x92, 0x3a, 0x38, 0x17, 0xbd, 0x9b, 0x9d, 0x0a, 0xf1,
	0xa0, 0x3a, 0xe8, 0xbd, 0xff, 0x71, 0xc7, 0xea, 0xfc, 0xee, 0x80, 0x77, 0x36, 0x19, 0x25, 0x02,
	0x13, 0xf1, 0x3d, 0x34, 0x57, 0x76, 0x3f, 0x79, 0x86, 0x21, 0x14, 0x3e, 0x2f, 0x6d, 0x52, 0x50,
	0x32, 0xae, 0x68, 0x85, 0xfc, 0x04, 0xff, 0x5f, 0xdb, 0xdd, 0x64, 0x7f, 0x09, 0x2d, 0x7c, 0x20,
	0xda, 0x7e, 0xa9, 0xc9, 0xf8, 0xfa, 0x01, 0x5a, 0xab, 0x5b, 0x88, 0xec, 0x22, 0xb6, 0xb8, 0xe6,
	0xdb, 0xcf, 0x8a, 0x5a, 0x73, 0xf9, 0x15, 0x54, 0x71, 0xac, 0x49, 0x0b, 0xcd, 0xf9, 0x7a, 0x6a,
	0x37, 0x73, 0x69, 0xc1, 0x76, 0x6d, 0xc2, 0x0c, 0xdb, 0xd2, 0x29, 0x35, 0x6c, 0xcb, 0x66, 0x92,
	0x56, 0xc8, 0x2d, 0xec, 0x95, 0x4e, 0x00, 0xf9, 0x02, 0x2f, 0x3d, 0x39, 0x63, 0xed, 0x17, 0x4f,
	0x9a, 0xb5, 0xdf, 0x4e, 0x1f, 0xea, 0xdd, 0xf3, 0x81, 0x4a, 0x04, 0x27, 0x5f, 0x82, 0x73, 0xc1,
	0x15, 0x59, 0x76, 0x5c, 0x1b, 0x0c, 0x21, 0xdd, 0xc8, 0x15, 0xf2, 0x15, 0x54, 0x07, 0x3c, 0x8e,
	0x48, 0xb1, 0xe5, 0x1e, 0xc3, 0x3a, 0xbf, 0x59, 0xe0, 0xf6, 0x45, 0x32, 0xe4, 0xe4, 0x18, 0x9a,
	0x78, 0x21, 0xef, 0x2d, 0x9d, 0x9d, 0x4c, 0x68, 0xb7, 0xb2, 0x3b, 0xba, 0x37, 0x69, 0x25, 0xc7,
	0xe6, 0x2d, 0x66, 0x46, 0xea, 0xaa, 0x1c, 0xfb, 0x06, 0xb6, 0x06, 0x79, 0x5f, 0x98, 0xa4, 0x16,
	0x46, 0xb4, 0x78, 0x63, 0x58, 0xd3, 0x7f, 0x74, 0xdf, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x87,
	0x75, 0x37, 0x37, 0xdd, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AlgorandClient is the client API for Algorand service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlgorandClient interface {
	AppendBlock(ctx context.Context, in *AppendBlockArgs, opts ...grpc.CallOption) (*AppendBlockRet, error)
	AppendTransaction(ctx context.Context, in *AppendTransactionArgs, opts ...grpc.CallOption) (*AppendTransactionRet, error)
	ProposeBlock(ctx context.Context, in *ProposeBlockArgs, opts ...grpc.CallOption) (*ProposeBlockRet, error)
	Vote(ctx context.Context, in *VoteArgs, opts ...grpc.CallOption) (*VoteRet, error)
	RequestBlockChain(ctx context.Context, in *RequestBlockChainArgs, opts ...grpc.CallOption) (*RequestBlockChainRet, error)
	NoticeFinalBlockValue(ctx context.Context, in *NoticeFinalBlockValueArgs, opts ...grpc.CallOption) (*NoticeFinalBlockValueRet, error)
}

type algorandClient struct {
	cc *grpc.ClientConn
}

func NewAlgorandClient(cc *grpc.ClientConn) AlgorandClient {
	return &algorandClient{cc}
}

func (c *algorandClient) AppendBlock(ctx context.Context, in *AppendBlockArgs, opts ...grpc.CallOption) (*AppendBlockRet, error) {
	out := new(AppendBlockRet)
	err := c.cc.Invoke(ctx, "/pb.Algorand/AppendBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorandClient) AppendTransaction(ctx context.Context, in *AppendTransactionArgs, opts ...grpc.CallOption) (*AppendTransactionRet, error) {
	out := new(AppendTransactionRet)
	err := c.cc.Invoke(ctx, "/pb.Algorand/AppendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorandClient) ProposeBlock(ctx context.Context, in *ProposeBlockArgs, opts ...grpc.CallOption) (*ProposeBlockRet, error) {
	out := new(ProposeBlockRet)
	err := c.cc.Invoke(ctx, "/pb.Algorand/ProposeBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorandClient) Vote(ctx context.Context, in *VoteArgs, opts ...grpc.CallOption) (*VoteRet, error) {
	out := new(VoteRet)
	err := c.cc.Invoke(ctx, "/pb.Algorand/Vote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorandClient) RequestBlockChain(ctx context.Context, in *RequestBlockChainArgs, opts ...grpc.CallOption) (*RequestBlockChainRet, error) {
	out := new(RequestBlockChainRet)
	err := c.cc.Invoke(ctx, "/pb.Algorand/RequestBlockChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorandClient) NoticeFinalBlockValue(ctx context.Context, in *NoticeFinalBlockValueArgs, opts ...grpc.CallOption) (*NoticeFinalBlockValueRet, error) {
	out := new(NoticeFinalBlockValueRet)
	err := c.cc.Invoke(ctx, "/pb.Algorand/NoticeFinalBlockValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlgorandServer is the server API for Algorand service.
type AlgorandServer interface {
	AppendBlock(context.Context, *AppendBlockArgs) (*AppendBlockRet, error)
	AppendTransaction(context.Context, *AppendTransactionArgs) (*AppendTransactionRet, error)
	ProposeBlock(context.Context, *ProposeBlockArgs) (*ProposeBlockRet, error)
	Vote(context.Context, *VoteArgs) (*VoteRet, error)
	RequestBlockChain(context.Context, *RequestBlockChainArgs) (*RequestBlockChainRet, error)
	NoticeFinalBlockValue(context.Context, *NoticeFinalBlockValueArgs) (*NoticeFinalBlockValueRet, error)
}

// UnimplementedAlgorandServer can be embedded to have forward compatible implementations.
type UnimplementedAlgorandServer struct {
}

func (*UnimplementedAlgorandServer) AppendBlock(ctx context.Context, req *AppendBlockArgs) (*AppendBlockRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendBlock not implemented")
}
func (*UnimplementedAlgorandServer) AppendTransaction(ctx context.Context, req *AppendTransactionArgs) (*AppendTransactionRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendTransaction not implemented")
}
func (*UnimplementedAlgorandServer) ProposeBlock(ctx context.Context, req *ProposeBlockArgs) (*ProposeBlockRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeBlock not implemented")
}
func (*UnimplementedAlgorandServer) Vote(ctx context.Context, req *VoteArgs) (*VoteRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vote not implemented")
}
func (*UnimplementedAlgorandServer) RequestBlockChain(ctx context.Context, req *RequestBlockChainArgs) (*RequestBlockChainRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestBlockChain not implemented")
}
func (*UnimplementedAlgorandServer) NoticeFinalBlockValue(ctx context.Context, req *NoticeFinalBlockValueArgs) (*NoticeFinalBlockValueRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoticeFinalBlockValue not implemented")
}

func RegisterAlgorandServer(s *grpc.Server, srv AlgorandServer) {
	s.RegisterService(&_Algorand_serviceDesc, srv)
}

func _Algorand_AppendBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendBlockArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorandServer).AppendBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Algorand/AppendBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorandServer).AppendBlock(ctx, req.(*AppendBlockArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Algorand_AppendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendTransactionArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorandServer).AppendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Algorand/AppendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorandServer).AppendTransaction(ctx, req.(*AppendTransactionArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Algorand_ProposeBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeBlockArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorandServer).ProposeBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Algorand/ProposeBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorandServer).ProposeBlock(ctx, req.(*ProposeBlockArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Algorand_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorandServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Algorand/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorandServer).Vote(ctx, req.(*VoteArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Algorand_RequestBlockChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBlockChainArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorandServer).RequestBlockChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Algorand/RequestBlockChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorandServer).RequestBlockChain(ctx, req.(*RequestBlockChainArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Algorand_NoticeFinalBlockValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeFinalBlockValueArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorandServer).NoticeFinalBlockValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Algorand/NoticeFinalBlockValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorandServer).NoticeFinalBlockValue(ctx, req.(*NoticeFinalBlockValueArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Algorand_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Algorand",
	HandlerType: (*AlgorandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendBlock",
			Handler:    _Algorand_AppendBlock_Handler,
		},
		{
			MethodName: "AppendTransaction",
			Handler:    _Algorand_AppendTransaction_Handler,
		},
		{
			MethodName: "ProposeBlock",
			Handler:    _Algorand_ProposeBlock_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _Algorand_Vote_Handler,
		},
		{
			MethodName: "RequestBlockChain",
			Handler:    _Algorand_RequestBlockChain_Handler,
		},
		{
			MethodName: "NoticeFinalBlockValue",
			Handler:    _Algorand_NoticeFinalBlockValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bc.proto",
}

// BCStoreClient is the client API for BCStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BCStoreClient interface {
	Get(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error)
	Send(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Result, error)
}

type bCStoreClient struct {
	cc *grpc.ClientConn
}

func NewBCStoreClient(cc *grpc.ClientConn) BCStoreClient {
	return &bCStoreClient{cc}
}

func (c *bCStoreClient) Get(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.BCStore/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bCStoreClient) Send(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.BCStore/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BCStoreServer is the server API for BCStore service.
type BCStoreServer interface {
	Get(context.Context, *Empty) (*Result, error)
	Send(context.Context, *Transaction) (*Result, error)
}

// UnimplementedBCStoreServer can be embedded to have forward compatible implementations.
type UnimplementedBCStoreServer struct {
}

func (*UnimplementedBCStoreServer) Get(ctx context.Context, req *Empty) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedBCStoreServer) Send(ctx context.Context, req *Transaction) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterBCStoreServer(s *grpc.Server, srv BCStoreServer) {
	s.RegisterService(&_BCStore_serviceDesc, srv)
}

func _BCStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BCStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BCStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BCStoreServer).Get(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BCStore_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BCStoreServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BCStore/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BCStoreServer).Send(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _BCStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BCStore",
	HandlerType: (*BCStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _BCStore_Get_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _BCStore_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bc.proto",
}

// ProbeClient is the client API for Probe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProbeClient interface {
	SendRPState(ctx context.Context, in *RPState, opts ...grpc.CallOption) (*Response, error)
	SendSLState(ctx context.Context, in *SLState, opts ...grpc.CallOption) (*Response, error)
	SendBlockChain(ctx context.Context, in *Blockchain, opts ...grpc.CallOption) (*Response, error)
}

type probeClient struct {
	cc *grpc.ClientConn
}

func NewProbeClient(cc *grpc.ClientConn) ProbeClient {
	return &probeClient{cc}
}

func (c *probeClient) SendRPState(ctx context.Context, in *RPState, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.Probe/SendRPState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeClient) SendSLState(ctx context.Context, in *SLState, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.Probe/SendSLState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeClient) SendBlockChain(ctx context.Context, in *Blockchain, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.Probe/SendBlockChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProbeServer is the server API for Probe service.
type ProbeServer interface {
	SendRPState(context.Context, *RPState) (*Response, error)
	SendSLState(context.Context, *SLState) (*Response, error)
	SendBlockChain(context.Context, *Blockchain) (*Response, error)
}

// UnimplementedProbeServer can be embedded to have forward compatible implementations.
type UnimplementedProbeServer struct {
}

func (*UnimplementedProbeServer) SendRPState(ctx context.Context, req *RPState) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRPState not implemented")
}
func (*UnimplementedProbeServer) SendSLState(ctx context.Context, req *SLState) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSLState not implemented")
}
func (*UnimplementedProbeServer) SendBlockChain(ctx context.Context, req *Blockchain) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBlockChain not implemented")
}

func RegisterProbeServer(s *grpc.Server, srv ProbeServer) {
	s.RegisterService(&_Probe_serviceDesc, srv)
}

func _Probe_SendRPState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServer).SendRPState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Probe/SendRPState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServer).SendRPState(ctx, req.(*RPState))
	}
	return interceptor(ctx, in, info, handler)
}

func _Probe_SendSLState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SLState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServer).SendSLState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Probe/SendSLState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServer).SendSLState(ctx, req.(*SLState))
	}
	return interceptor(ctx, in, info, handler)
}

func _Probe_SendBlockChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blockchain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServer).SendBlockChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Probe/SendBlockChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServer).SendBlockChain(ctx, req.(*Blockchain))
	}
	return interceptor(ctx, in, info, handler)
}

var _Probe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Probe",
	HandlerType: (*ProbeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRPState",
			Handler:    _Probe_SendRPState_Handler,
		},
		{
			MethodName: "SendSLState",
			Handler:    _Probe_SendSLState_Handler,
		},
		{
			MethodName: "SendBlockChain",
			Handler:    _Probe_SendBlockChain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bc.proto",
}
